const solution = require('./solution')
const assert = require('assert')

assert.equal(solution(1), 'I')
assert.equal(solution(2), 'II',)
assert.equal(solution(3), 'III',)
assert.equal(solution(4), 'IV',)
assert.equal(solution(5), 'V',)
assert.equal(solution(9), 'IX',)
assert.equal(solution(10), 'X',)
assert.equal(solution(11), 'XI')
assert.equal(solution(19), 'XIX')
assert.equal(solution(22), 'XXII')
assert.equal(solution(15), 'XV')
assert.equal(solution(1666), 'MDCLXVI')